[package]
name = "polymerust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio-seq = "0.11.2"
rand = "0.8.5"
seq_io = "0.3.2"

[[bin]]
name = "polymerust-cli"
path = "src/main.rs"
